# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c9cae7b408a9f8447b2783a1dd0668cfbc5638c10d275e49e68b0f36786783bf682bb21a9e103a5dfdcf893f53f615b1f128b06b6ad412ea2d70d87842efa16a

test:
  secret_key_base: 6706b8ca4a9059bf8da0b6284fc92c8258159b0f1e95930102f29fc1f08128ea127f6b0664a5bf49cf8d347b1c326444697f35221fb96146aa32a9f6fde87e46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
